### ISSUE TITLE
javascript client

### ISSUE THREAD

**Issue by jparish3** [elastic/elasticsearch-chatgpt-php#1]
can this be replicated with the elasticsearch javascript client? Has there been any follow up to the blog post in terms of ....'we will definitely investigate further the possibility to query Elasticsearch in natural language using ChatGPT, as well as other LLM models that are becoming more and more popular'

**Comment by ezimuel** [comment]
We are experimenting this approach but nothing stable at the moment. We are also investigating in Python ecosystem.
